version: '2'
services:
  web:
    image: "calpolypomona/cpp-parking-backend:latest"
    ports:
     - "9000:9000"
    depends_on:
      - redis
  redis:
    image: "redis:latest"
    entrypoint:
      - redis-server
      - --notify-keyspace-events
      - AKE
networks:
  default:
    external:
      name: cpp-parking-net
